version: "3.8"

services: 
  app:
    image: nodejs
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
      
  
  mysql_server:
   image: mysql:8.0
   ports:
     - 3306:3306
   environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD
      
  nginx:
    image: nginx123
    build:
      context: .
      dockerfile: nginxdockerfile
    hostname: nginx
    ports:
      - "80:80" 
      - "443:443"
    depends_on:
      - app

#Docker Networks


    